name: Build and Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          mkdir build
          pip install -r requirements.txt -t build/
          cp lambda_function.py build/

      - name: Create deployment package
        run: |
          cd build
          zip -r ../lambda_qr_code.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name GenerateQRCode --zip-file fileb://lambda_qr_code.zip
